### ISSUE TITLE
Napaka v imenu

### ISSUE THREAD

**Issue by sbor-si** [bostjan2016/MIUI-7-SLOVENIAN#1]
![screenshot_2016-04-04-20-51-35_com android thememanager 1](https://cloud.githubusercontent.com/assets/18280508/14274134/cd2164e2-fb0f-11e5-8f4c-4e2935bdb442.png)
Kot je razvidno - pri iskanju melodije zvonjenja - izbira na telefon naložene melodije se pojavi 1x Glazba in 1x Glasba - seveda je prav Glasba. 
Drugače pa vse pohvale za prevod

**Comment by MASVA** [comment]
fixed
lp
