### ISSUE TITLE
ura -> nastavitve

### ISSUE THREAD

**Issue by majzl** [bostjan2016/MIUI-7-SLOVENIAN#2]
![screenshot_2016-04-12-15-52-13_com android deskclock](https://cloud.githubusercontent.com/assets/18439134/14489182/140093a8-016c-11e6-88e2-f501da67e646.png)

"Samodejno utišaš" -> "Alarm se izključi čez 10 min" ali "Alarm se bo izključil čez 10 min"

**Comment by majzl** [comment]
PS: Pohvala, da si se lotil prevoda tega super roma. Pred časom sem že jaz razmisljal, da bi se lotil, vendar mi manjka znanja in časa. Bom pa z veseljem sporočal "napake" :)

Sedaj bo lahko imela končno tudi moja mami xiaomi-jev telefon.

Še enkrat pohvaljen.

**Comment by bostjan2016** [comment]
Hvala za pohvalo!
Glede napak pa malo več tukaj:
http://adria.mobiledevs.net/threads/nov-slo-rom-6-4-7.798/#post-2971

Tako da: vse se bo popravilo oz. uredilo, a ne kar najkasneje takoj.
Napake kar javljaj, zaželjeno s screenshotom. Morda samo pripomba. Javljaj
direkt na forum, ne preko ps ali githuba, Tako da tudi ostali lahko vidijo
kaj je že bilo javljeno.
Hvala in lp

Dne 13. april 2016 11:43 je majzl notifications@github.com napisal/-a:

**Comment by bostjan2016** [comment]
Fixed
