### ISSUE TITLE
imenik / telefon -> rumene strani

### ISSUE THREAD

**Issue by majzl** [bostjan2016/MIUI-7-SLOVENIAN#3]
![screenshot_2016-04-12-15-56-07_com miui yellowpage](https://cloud.githubusercontent.com/assets/18439134/14489371/15afa15c-016d-11e6-9f60-74f11cdac0d0.png)

"Pazi na goljufije" -> "Pripomba Nekatere informacije ... uporabniki **in** Politika...""

**Comment by bostjan2016** [comment]
ok

2016-04-13 11:46 GMT+02:00 majzl notifications@github.com:

**Comment by bostjan2016** [comment]
Fixed
