### ISSUE TITLE
imenik / telefon -> o funkciji

### ISSUE THREAD

**Issue by majzl** [bostjan2016/MIUI-7-SLOVENIAN#4]
![screenshot_2016-04-12-15-56-22_com miui yellowpage](https://cloud.githubusercontent.com/assets/18439134/14489435/72fe6fdc-016d-11e6-86ab-ba30ae14aedc.png)

"O funkciji" -> "Pripomba Nekatere informacije ... uporabniki **in** Politika...""

**Comment by bostjan2016** [comment]
ok

2016-04-13 11:48 GMT+02:00 majzl notifications@github.com:

**Comment by bostjan2016** [comment]
Fixed
