### ISSUE TITLE
varnost -> baterija

### ISSUE THREAD

**Issue by majzl** [bostjan2016/MIUI-7-SLOVENIAN#5]
Pri preostanku časa je prevod še v hrvaščini -> "2 dana 22 sati preostanka". Predvidevam, da si vzel hrvaščino kot izhodišče za prevod.

"Profil baterije"  -> "My profile" prevod v "Moj profil"?
![screenshot_2016-04-12-16-03-49_com miui securitycenter](https://cloud.githubusercontent.com/assets/18439134/14489489/cd35e7b4-016d-11e6-8d9d-f6b1c88c92d3.png)

"nastavi" -> "indikator baterije" -> "Top bar" prevod v "zgornja / vrhnja vrstica" (boljše ideje nimam =) ).
![screenshot_2016-04-12-16-04-49_com miui securitycenter](https://cloud.githubusercontent.com/assets/18439134/14489743/31bbdf94-016f-11e6-8fab-2b9feefd185b.png)

**Comment by bostjan2016** [comment]
ok

2016-04-13 12:01 GMT+02:00 majzl notifications@github.com:

**Comment by bostjan2016** [comment]
Fixed
