### ISSUE TITLE
prijava napake (MIUI središče za prijavo napak)

### ISSUE THREAD

**Issue by majzl** [bostjan2016/MIUI-7-SLOVENIAN#6]
Jaz osebno bi prevod "poraba moči" zamenjal s "poraba baterije / energije".
![screenshot_2016-04-12-16-10-41_com miui bugreport](https://cloud.githubusercontent.com/assets/18439134/14489840/b7ff38e4-016f-11e6-9a4f-1fb37bd67102.png)

**Comment by majzl** [comment]
Na hitro sem šel čez aplikacije in našel predhodno prijavljene "napake". Ko bom imel čas grem še čez nastavitve.

**Comment by bostjan2016** [comment]
Settings so bile posodobljene te dni. Počakaj do petka na nov rom!

2016-04-13 12:06 GMT+02:00 majzl notifications@github.com:

**Comment by bostjan2016** [comment]
fixed
