### ISSUE TITLE
Slovenščina

### ISSUE THREAD

**Issue by sbor-si** [bostjan2016/MIUI-7-SLOVENIAN#7]
Za rezervo uporabljam Mi Cloud sinhronizacijo, pa v prevodu obstaja kup napak, ki so mi padle v oči.
![screenshot_2016-04-18-12-08-30_com miui gallery](https://cloud.githubusercontent.com/assets/18280508/14601852/dac0c944-0564-11e6-81da-dc89ee230f0a.png)

pa še v Mi Remote - trenutak
![screenshot_2016-04-18-12-57-55_com duokan phone remotecontroller](https://cloud.githubusercontent.com/assets/18280508/14601954/65a7a80c-0565-11e6-8184-decb3027028c.png)

**Comment by bostjan2016** [comment]
O podobnih stvareh sem že pisal:
"Ja...
Takih in podobnih napakic v prevajanju je še malo morje kot sem že napisal.
Prevajali smo iz hrvaščine, dela ogromno, še drugi opravki...
Ko je prišla ven prva verzija roma (pa tudi še zdaj) najprej težimo k temu
da se najde in odpravi napake v uporabnosti.
Ne mislim reči da bomo ostalo zanemarili ampak da se bo počasi- teden za
tednom izboljševalo.
Najprej je pač bila želja narediti delujoč slo rom, potem pa popravljanje
napakic. Kar pa vzame kar nekaj časa.
Vsak teden se bo najprej pregledalo in popravilo aplikacije tako da ne bo
uprabnih napak, naredilo posodobitve, potem pa še korekcija že obstoječih
stvari."

Tako da: hvala za info in prosim za malo potrpljenja. Bomo uredili.

2016-04-18 13:02 GMT+02:00 sbor-si notifications@github.com:

**Comment by sbor-si** [comment]
Razumem in pohvalim trud za slovensko različico.
Če rabite pomoč bi lahko kakšno urico časa namenil...

**Comment by bostjan2016** [comment]
Hvala za pohvalo!
Če bi res lahko vzel kako uro časa za napake- oz. odpravljanje bi bilo zelo dobrodošlo. Takih ponudb še ni bilo...
Z obzirom da pišeš preko Github-a predvidevam da imaš malo več znanja o teh stvareh. Torej: tu lahko vidiš in preneseš moj repo, ga pregledaš in če kje najdeš kaj čudnega mi javiš kje ta čudna stvar je in jo jaz pogledam in če bo treba popravim.
Npr. Settings imajo cca 4500 vrstic. V njih najti napako...Misija nemogoče- skoraj
Za kaj več me kontaktiraj direktno na 
bostjan.rebolj@gmail.com
LP
