### ISSUE TITLE
NetworkAssistant2.apk

### ISSUE THREAD

**Issue by usnkreal** [bostjan2016/MIUI-7-SLOVENIAN#9]
NetworkAssistant2.apk/res/layout-sl/network_speed_view.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/number').
NetworkAssistant2.apk/res/layout-sl/network_speed_view.xml:5: error: Error: No resource found that matches the given name (at 'layout_toRightOf' with value '@id/number').
NetworkAssistant2.apk/res/layout-sl/network_speed_view.xml:5: error: Error: No resource found that matches the given name (at 'layout_alignTop' with value '@id/number').
NetworkAssistant2.apk/res/layout-sl/network_speed_view.xml:6: error: Error: No resource found that matches the given name (at 'id' with value '@id/unit').

**Comment by bostjan2016** [comment]
Ker ne vidim nobenega problema zapiram prijavo napake

2016-05-21 16:35 GMT+02:00 usnkreal notifications@github.com:
